version: 2.1

parameters:
  run-api-workflow:
    type: boolean
    default: false
  run-app-workflow:
    type: boolean
    default: false
  run-auth-workflow:
    type: boolean
    default: false
  run-gateway-workflow:
    type: boolean
    default: false

jobs:
  common-pre:
    docker:
      - image: cimg/node:lts
    steps:
      - run: echo 'Jobs with `common-` prefix are intended to be shared among modules'
  building-all:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - when:
          condition: <<pipeline.parameters.run-api-workflow>>
          steps:
            - run: echo 'Hello world from api package!'
      - when:
          condition: <<pipeline.parameters.run-app-workflow>>
          steps:
            - run: echo 'Hello world from app package!'
      - when:
          condition: <<pipeline.parameters.run-auth-workflow>>
          steps:
            - run: echo 'Hello world from auth package!'
      - when:
          condition: <<pipeline.parameters.run-gateway-workflow>>
          steps:
            - run: echo 'Hello world from gateway package!'

workflows:
  all-workflow:
    jobs:
      - common-pre
      - building-all:
          requires:
            - common-pre
